# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-15-intel

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
             uname -a # runs in single line and uname here not executed 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "uname -a:"
          uname -a
          echo "df -h ./:"
          df -h ./
          echo "xcode info:"
          xcode-select -p || echo "xcode-select -p failed"
          xcodebuild -version || echo "xcodebuild -version failed"
          echo "No version given, resolving latest stable..."
          curl_version=$(curl --fail-with-body --max-time 30 --no-progress-meter \
              'https://versionhistory.googleapis.com/v1/chrome/platforms/linux/channels/stable/versions/all/releases?order_by=version%20desc')
          echo "curl_version:$curl_version"
          version =  $(echo $curl_version | jq -r '.releases[0].version')
          echo "version:$version"
          maccurl_version=$(curl --fail-with-body --max-time 30 --no-progress-meter \
              'https://versionhistory.googleapis.com/v1/chrome/platforms/mac/channels/stable/versions/all/releases?order_by=version%20desc')
          echo "maccurl_version:$curl_version"
          macversion =  $(echo $maccurl_version | jq -r '.releases[0].version')
          echo "macversion:$macversion"
